// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCx18oFM8deZvzoEbgAKmwYkAkZzFqm5qU',
    appId: '1:1034382745774:android:8bcc0d9cf7c9e9d6ec4d3f',
    messagingSenderId: '1034382745774',
    projectId: 'engeneering-design-2022',
    databaseURL: 'https://engeneering-design-2022-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'engeneering-design-2022.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKcHqNzShNnDHWOiru4ERIWn-N2jcF7hY',
    appId: '1:1034382745774:ios:6a73849086a47208ec4d3f',
    messagingSenderId: '1034382745774',
    projectId: 'engeneering-design-2022',
    databaseURL: 'https://engeneering-design-2022-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'engeneering-design-2022.appspot.com',
    iosClientId: '1034382745774-1ihuhaq8pdu94e0ojpjt085svtbbjl9k.apps.googleusercontent.com',
    iosBundleId: 'com.foodiee.shelfLifePrototype',
  );
}
